<a href="https://colab.research.google.com/github/akarshpyr/Python-codes/blob/main/chi_2b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Null hypothesis: All the defective percentages are same;      
Alternate Hypothesis: At least one among the centers have different defect percentage.

In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
df = pd.read_csv('/content/Costomer+OrderForm.csv')

In [3]:
df

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [5]:
a = df['Phillippines'].value_counts()

In [7]:
b = df['India'].value_counts()

In [8]:
c= df['Indonesia'].value_counts()

In [9]:
d = df['Malta'].value_counts()

In [10]:
obs = np.array([[a[0],b[0],c[0],d[0]],[a[1],b[1],c[1],d[1]]])

In [11]:
obs

array([[271, 280, 267, 269],
       [ 29,  20,  33,  31]])

In [12]:
chi_2 = stats.chi2_contingency(obs)

In [13]:
chi_2

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [14]:
chi2_statistic = chi_2[0]

In [16]:
p_value = chi_2[1]

In [17]:
expected_values = chi_2[3]

In [18]:
expected_values

array([[271.75, 271.75, 271.75, 271.75],
       [ 28.25,  28.25,  28.25,  28.25]])

For a dof =3 and alpha =0.05. The chi2-critical is:

In [19]:
chi2_critical = stats.chi2.ppf(q=1-0.05,df=3)

In [20]:
chi2_critical

7.814727903251179

In [21]:
alpha = 0.05

In [23]:
if p_value>alpha:
  print('We fail to reject null hypothesis')
else:
  print('We accept alternative hypothesis')

We fail to reject null hypothesis
