<a href="https://colab.research.google.com/github/akarshpyr/Python-codes/blob/main/Featureengi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [6]:
newfile = '/content/pima-indians-diabetes.csv'

In [4]:
data

6  148  72  35    0  33.6  0.627  50  1
0     1   85  66  29    0  26.6  0.351  31  0
1     8  183  64   0    0  23.3  0.672  32  1
2     1   89  66  23   94  28.1  0.167  21  0
3     0  137  40  35  168  43.1  2.288  33  1
4     5  116  74   0    0  25.6  0.201  30  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
762  10  101  76  48  180  32.9  0.171  63  0
763   2  122  70  27    0  36.8  0.340  27  0
764   5  121  72  23  112  26.2  0.245  30  0
765   1  126  60   0    0  30.1  0.349  47  1
766   1   93  70  31    0  30.4  0.315  23  0

[767 rows x 9 columns]

In [5]:
names = ['preg','plas','pres','skin','test','mass','pedi','age','class']

In [9]:
df = pd.read_csv(newfile,names = names)

In [40]:
ddf = df

In [11]:
array = df.values

In [12]:
x = array[:,0:8]
y= array[:,8]

In [15]:
test = SelectKBest(score_func = chi2, k=4)
fit = test.fit(x,y)

In [16]:
test

SelectKBest(k=4, score_func=<function chi2 at 0x7fbb1383e440>)

In [17]:
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(x)

[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]


In [18]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [19]:
names = ['preg','plas','pres','skin','test','mass','pedi','age','class']
newfile = '/content/pima-indians-diabetes.csv'
array = df.values
x = array[:,0:8]
y= array[:,8]


In [22]:
model = LogisticRegression(max_iter=400)
rfe = RFE(model)

In [23]:
fit = rfe.fit(x,y)

In [24]:
fit.n_features_

4

In [25]:
fit.support_

array([ True,  True, False, False, False,  True,  True, False])

In [35]:
a = fit.ranking_
a

array([1, 1, 3, 5, 4, 1, 1, 2])

In [29]:
df = pd.DataFrame(columns = ['rank','names'])

In [30]:
df

Empty DataFrame
Columns: [rank, names]
Index: []

In [36]:
dic = { 'names':['preg','plas','pres','skin','test','mass','pedi','age'], 'rank' : a }

In [37]:
df1 = pd.DataFrame(dic)

In [38]:
df1

names  rank
0  preg     1
1  plas     1
2  pres     3
3  skin     5
4  test     4
5  mass     1
6  pedi     1
7   age     2

In [45]:
names = ['preg','plas','pres','skin','test','mass','pedi','age','class']
newfile = '/content/pima-indians-diabetes.csv'
b = pd.read_csv(newfile,names=names)

In [46]:
b

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [47]:
array = b.values
x = array[:,0:8]
y= array[:,8]


In [49]:
from sklearn.tree import DecisionTreeClassifier

In [50]:
model = DecisionTreeClassifier()

In [51]:
model.fit(x,y)

DecisionTreeClassifier()

In [52]:
print(model.feature_importances_)

[0.071 0.304 0.11  0.023 0.037 0.221 0.118 0.116]


In [1]:
from sklearn.model_selection import train_test_split

In [2]:
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np
filename = '/content/pima-indians-diabetes.csv'
names = ['preg','plas','pres','skin','test','mass','pedi','age','class']
df = pd.read_csv(filename,names=names)

In [3]:
df

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [4]:
array = df.values

In [5]:
x = array[:,0:8]
y = array[:,8]

In [6]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=10)

In [7]:
model = LogisticRegression(max_iter=500)
model.fit(x_train,y_train)


LogisticRegression(max_iter=500)

In [8]:
model.score(x_test,y_test)

0.7598425196850394

In [9]:
from sklearn.model_selection import KFold,cross_val_score

In [11]:
kfold = KFold(n_splits=7)
result = cross_val_score(model,x,y,cv=kfold)

In [12]:
result

array([0.74545455, 0.79090909, 0.69090909, 0.79090909, 0.77272727,
       0.85321101, 0.77981651])

In [14]:
result.mean()

0.7748480876921244

In [15]:
result.std()

0.045662703961971314

In [16]:
from sklearn.model_selection import LeaveOneOut

In [17]:
loocv = LeaveOneOut()

In [18]:
results = cross_val_score(model,x,y,cv=loocv)

In [19]:
results

array([1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
       1., 1., 0., 1., 1.

In [20]:
results.mean()

0.7760416666666666

In [21]:
results.std()

0.4168944689773287